const WINDOW_RATE_LIMIT_CONFIG = {
    REQUEST_COUNT: 100,
    WINDOW_SIZE: 1000
};

const TOKEN_BUCKET_RATE_LIMIT_CONFIG = {
    MAX_TOKENS: 10,
    REFILL_RATE: 5
};

export { WINDOW_RATE_LIMIT_CONFIG, TOKEN_BUCKET_RATE_LIMIT_CONFIG };