services:
  otel-collector:
    image: otel/opentelemetry-collector
    volumes:
      - ./otel-collector.yaml:/etc/otelcol/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
  
  tempo:
      image: grafana/tempo:latest

      command:
        - "-config.file=/etc/tempo/tempo.yaml"

      volumes:
        - ./tempo/tempo.yaml:/etc/tempo/tempo.yaml:ro

      ports:
        - "3200:3200"
        
  grafana:
    image: grafana/grafana:latest

    ports:
      - "3000:3000"

    depends_on:
      - tempo
